services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5175:5175'
    networks:
      - avto_rent_seo_default

networks:
  avto_rent_seo_default:
    driver: bridge